version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name final-codedeploy-app --s3-location s3://final-kadai/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src